twig:
  default_path: "%kernel.project_dir%/templates"
  file_name_pattern: ["*.twig"]
  form_themes: ["bootstrap_5_layout.html.twig"]

  # globals
  globals:
    MA_GLOBALE: "Ceci est la valeur de MA_GLOBALE"

when@test:
  twig:
    strict_variables: true
